[tool.poetry]
packages = [
    { include = "brain_games" }
]
[tool.poetry.scripts]
brain-games = "brain_games.scripts.brain_games:main"
name = "yerkebulanali_brain_games"
version = "0.1.0"
description = ""
authors = ["Yerkebulan <yerkebulanali@gmail.com>"]

[tool.poetry.dependencies]
python = "^2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
